### ISSUE TITLE
The missing Gist source for RandomUtil

### ISSUE THREAD

**Issue by Moonlight-Angel** [WolfDan/Dofux#1]
Hi,

I saw you were missing a Gist link for your RandomUtil module.
I think I've found it here. https://gist.github.com/ahmadshah/8d978bbc550128cca12dd917a09ddfb7

Sorry for not making a PR for this one, I figured out it wasn't worth forking the whole repo for such a tiny change.
Cheers.

**Comment by WolfDan** [comment]
So many thanks! I just update the readme :D
